# Generated by Django 5.0.1 on 2024-04-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='cra.course')),
            ],
        ),
    ]
